baseURL = 'https://your-username.github.io/facebook-blog/'
languageCode = 'ja'
title = 'kamiyn Book Log'
theme = 'ananke'

[params]
  author = "kamiyn"
  description = "kamiyn Book Log"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 20

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "投稿一覧"
    url = "/posts/"
    weight = 10
